server:
  port: 8080

spring:
  application:
    name: starter-app

  config:
    import: "application-core.yml"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "303256356500-5u5qfqnedi5sj1te4kffa1ecacsbkhao.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
    jwt:
      access-token:
        secret-key: "access-beekei"
        expired-time: 300000 # 1000 * 60 * 5 = 5?
      refresh-token:
        secret-key: "refresh-beekei"
        expired-time: 604800000 # 1000 * 60 * 60 * 24 * 7 = 7?

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /resources/**

springdoc:
  packages-to-scan: com.starter.app
  api-docs:
    enabled: true
    path: /api/docs/json
  swagger-ui:
    enabled: true
    path: /api/docs
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: false
  model-and-view-allowed: true
  group-configs:
    - group: V1
      paths-to-match:
        - /api/v1/**